services:
  - type: web
    name: queenkoba-backend
    env: python
    buildCommand: pip install -r app/requirements.txt
    startCommand: gunicorn queenkoba_postgresql:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: queenkoba-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true

databases:
  - name: queenkoba-db
    databaseName: queenkoba
    user: queenkoba
